A = input("Please enter the string A : ")
B = input("Please enter the string B : ")
print ("-"*50)
print (f"A number of character in A is {len(A)}")
print (f"A number of character in B is {len(set(B))}")
print (f"A number of character in both A and B is {len(set(A) & set(B))} ")
print (f"Chareacter in A but not in B is {(set(A) - set(B))}")
print (f"Chareacter in B but not in A is {(set(B) - set(A))}")
print (f"Chareacter in A or B but not in both A and B is {(set(A) ^ set(B))}")
print (f"All characters in A or B is {(set(A) | set(B))}")